name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version of HDX MCP Server
          required: true
        - label: I have checked the documentation and troubleshooting guide
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Call tool '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Python version: [e.g., 3.11.5]
        - HDX MCP Server version: [e.g., 1.0.0]
        - UV version: [e.g., 0.1.0]
        - MCP Client: [e.g., Claude Desktop, MCP Inspector]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Please include any relevant error messages or log output
      placeholder: Paste error messages or logs here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive information like API keys)
      placeholder: |
        # .env file (redacted)
        HDX_BASE_URL=https://hapi.humdata.org/api/v2
        HDX_TIMEOUT=30.0
        # etc.
      render: shell

  - type: dropdown
    id: transport
    attributes:
      label: Transport Type
      description: Which transport are you using?
      options:
        - stdio (default)
        - http
        - both
        - not sure
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: hdx_api
    attributes:
      label: HDX API Status
      description: Please check your HDX API access
      options:
        - label: I have a valid HDX API key
        - label: I can access HDX API directly (outside of this MCP server)
        - label: The issue occurs even with a fresh API key
